name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install gems
      run: |
        sudo gem install brakeman -v 4.5.0
    - name: brakeman report
      run: |
        brakeman -f json > brakeman.json || exit 0

    
