name: Brakeman

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Brakeman
      uses: devmasx/brakeman-linter-action@v1.0.0
      env:
        GITHUB_TOKEN: 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
