name: Brakeman

on: [pull_request,push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install brakeman
      run: |
        sudo gem install brakeman -v 5.2.0
    - name: brakeman 
      run: |
        brakeman -f sarif -o results.sarif || exit 0
    - name: show
      run: |
        cat results.sarif 
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
    - name: Clean
      run : |
        rm -rf results.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        #category: my-analysis-tool

        
