name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install gems
      run: |
        sudo gem install brakeman -v 4.5.0
    - name: brakeman report
      run: |
        brakeman || exit 0
    - name: Brakeman action
      # You may pin to the exact commit or the version.
      # uses: artplan1/brakeman-action@164f2a414affc6358a78b19f530071975f353d17
      uses: artplan1/brakeman-action@v1.2.1


    
