name: Rubocop

on: 
  push:
    branches:
      - master
jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v2
        with:
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop -f json -o output.json
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.externalIssuesReportPaths=output.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
